# site
title: Leonhard von Sydow
baseurl: "/"
url: "https://leonhardsydow.github.io"
favicon: "/assets/img/hexa.svg"

# bio
header: Leonhard von Sydow
desc: >
  Munich based IT Consultant, Software Developer and currently studying to become a M. Sc. in Business Informatics at Munich University of Applied Sciences.

# posts
date_format: "%Y"
post_title: Activity
post_date: Year
post_cat: Type

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock