# site
title: Leonhard von Sydow
baseurl: "/"
url: "https://leonhard-sydow.com"
favicon: "/assets/img/hexa.svg"
tagline: "Leonhard von Sydows Website he made about himself"
author: "Leonhard von Sydow"
social:
  name: Leonhard von Sydow
  links: 
  - https://github.com/leonhardsydow
  - https://de.linkedin.com/in/leonhard-v-sydow-1765841a8

# bio
header: Leonhard von Sydow
desc: >
  Munich based Atlassian Consultant and Full Stack Developer. M. Sc. in Business Informatics.

# posts
date_format: "%Y"
post_title: Activity
post_date: Year
post_cat: Type

# post detail
prev-next: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock